### PR TITLE
[examples] Initialize backprop cases on ventus

### PR DESCRIPTION
**Pull request by xvyv99**

### CODE REVIEW

**Comment by xlinsist** [comment]
I think backprop_official_import_llvm_to_llvmir.ll should also be added.

**Comment by xlinsist** [comment]
`make backprop_official_import_llvm.mlir` seems not to work in my machine. I got:
image

**Comment by xlinsist** [comment]
Running `make make-spike-test` in my local machine leads to "/usr/bin/ld: cannot find -lspike_main: No such file or directory". Having changed my local path, is there something I have missed?
image

IMO, if we can follow the official guide to run this example on spike without modifying source code like test.cpp, maybe we can just reuse the official guide like the makefile in "ventus-vectoradd" directory does.

**Comment by xvyv99** [comment]
> I think backprop_official_import_llvm_to_llvmir.ll should also be added.

ok

**Comment by xvyv99** [comment]
> `make backprop_official_import_llvm.mlir` seems not to work in my machine. I got: image

Maybe you are using llvm-project that is not from ventus-gpgpu. I get the same error when using llvm-project that is not from ventus-gpgpu.

**Comment by xvyv99** [comment]
> `SPIKE_TARGET_DIR := ${SPIKE_SRC_DIR}/spike_main` seems like a line of hard code?
> 
> IMO, if we can follow the official guide to run this example on spike without modifying source code like test.cpp(other than changing `vecadd.riscv` to `bprop.riscv`), maybe we can just reuse the official guide like the makefile in "ventus-vectoradd" directory does.

The driver directory is from the gpgpu-testcase/driver directory of the ventus-gpgpu-isa-simulator project. The only modification is changing the filename from vecadd.riscv to backprop.riscv in test.cpp. I also considered directly using this test case, but it didn't feel elegant to change backprop.riscv to vecadd.riscv. Moreover, I thought perhaps we could add some correctness testing once we get it running.

**Comment by xlinsist** [comment]
> > `SPIKE_TARGET_DIR := ${SPIKE_SRC_DIR}/spike_main` seems like a line of hard code?
> > IMO, if we can follow the official guide to run this example on spike without modifying source code like test.cpp(other than changing `vecadd.riscv` to `bprop.riscv`), maybe we can just reuse the official guide like the makefile in "ventus-vectoradd" directory does.
> 
> The driver directory is from the gpgpu-testcase/driver directory of the ventus-gpgpu-isa-simulator project. The only modification is changing the filename from vecadd.riscv to backprop.riscv in test.cpp. I also considered directly using this test case, but it didn't feel elegant to change backprop.riscv to vecadd.riscv. Moreover, I thought perhaps we could add some correctness testing once we get it running.

Yes.It makes sense to me.

**Comment by xlinsist** [comment]
> > `make backprop_official_import_llvm.mlir` seems not to work in my machine. I got: image
> 
> Maybe you are using llvm-project that is not from ventus-gpgpu. I get the same error when using llvm-project that is not from ventus-gpgpu.

Looks like we need to fix llvm version during the developments. These modifications will be left to another PR.

**Pull request merged**
